apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-tornado-framework-rc
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-rc
  template:
    metadata:
      labels:
        app: py-rc
    spec:
      containers:
        - name: py-rc-container
          imagePullPolicy: Always
          image: docker.io/alaaamin/reload-count-tornado-py-app
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
